config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  resources :votos
  get 'pages/batman'
  get 'pages/batman_vs_superman'
  get 'pages/superman'

root 'pages#batman_vs_superman'

end

app/models/voto.rb
class Voto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def page1
  end

  def page2
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def batman
  end

  def superman
  end

  def batman_vs_superman
  end
  
end

app/controllers/votos_controller.rb
class VotosController < ApplicationController
  before_action :set_voto, only: [:show, :edit, :update, :destroy]

  # GET /votos
  # GET /votos.json
  def index
    @votos = Voto.all
  end

  # GET /votos/1
  # GET /votos/1.json
  def show
  end

  # GET /votos/new
  def new
    @voto = Voto.new
  end

  # GET /votos/1/edit
  def edit
  end

  # POST /votos
  # POST /votos.json
  def create
    @voto = Voto.new(voto_params)

    respond_to do |format|
      if @voto.save
        format.html { redirect_to @voto, notice: 'Voto was successfully created.' }
        format.json { render :show, status: :created, location: @voto }
      else
        format.html { render :new }
        format.json { render json: @voto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votos/1
  # PATCH/PUT /votos/1.json
  def update
    respond_to do |format|
      if @voto.update(voto_params)
        format.html { redirect_to @voto, notice: 'Voto was successfully updated.' }
        format.json { render :show, status: :ok, location: @voto }
      else
        format.html { render :edit }
        format.json { render json: @voto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votos/1
  # DELETE /votos/1.json
  def destroy
    @voto.destroy
    respond_to do |format|
      format.html { redirect_to votos_url, notice: 'Voto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voto
      @voto = Voto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voto_params
      params.require(:voto).permit(:heroe, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/votos_helper.rb
module VotosHelper
end

app/views/experiments/page1.html.erb
<h1>Experiments#page1</h1>
<p>«Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.»
«Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.»</p>

app/views/experiments/page2.html.erb
<h1>Experiments#page2</h1>
<p>«Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.»
«Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.»</p>

app/views/experiments/page3.html.erb
<div class= "page3">
<h1>Experiments#page3</h1>
<p>«Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.»
«Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.»</p>


</div>

app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="page1">Page1 <span class="sr-only">(current)</span></a></li>
        <li><a href="page2">Page2</a></li>
        <li><a href="page3">Page3</a></li>
        
      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= render 'layouts/bootstrap' %>

  <%= render 'layouts/navbar' %>

  
  <title>Superheroes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>



<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/pages/batman.html.erb
<h1>"I am Batman"</h1>

app/views/pages/batman_vs_superman.html.erb
<a href="batman"><img style="width: 50%; height: 50%; float: left;" src="/batman.jpg"></a>
<a href="superman"><img style="width: 50%; height: 50%; float: right;" src="/superman.jpg"></a>

app/views/pages/superman.html.erb
<h1>"This looks like a job for Superman"</h1>

app/views/votos/_form.html.erb
<%= form_for(@voto) do |f| %>
  <% if @voto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voto.errors.count, "error") %> prohibited this voto from being saved:</h2>

      <ul>
      <% @voto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :heroe %><br>
    <%= f.text_field :heroe %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votos/edit.html.erb
<h1>Editing Voto</h1>

<%= render 'form' %>

<%= link_to 'Show', @voto %> |
<%= link_to 'Back', votos_path %>

app/views/votos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Votos</h1>

<table>
  <thead>
    <tr>
      <th>Heroe</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votos.each do |voto| %>
      <tr>
        <td><%= voto.heroe %></td>
        <td><%= voto.email %></td>
        <td><%= link_to 'Show', voto %></td>
        <td><%= link_to 'Edit', edit_voto_path(voto) %></td>
        <td><%= link_to 'Destroy', voto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voto', new_voto_path %>

app/views/votos/new.html.erb
<h1>New Voto</h1>

<%= render 'form' %>

<%= link_to 'Back', votos_path %>

app/views/votos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Heroe:</strong>
  <%= @voto.heroe %>
</p>

<p>
  <strong>Email:</strong>
  <%= @voto.email %>
</p>

<%= link_to 'Edit', edit_voto_path(@voto) %> |
<%= link_to 'Back', votos_path %>